title: Capsailer
description: A CLI tool for delivering Kubernetes applications into air-gapped (offline) environments
url: https://capsailer.dev
baseurl: ""
github_username: capsailer
github_repo: capsailer-cli
repo_url: https://github.com/capsailer/capsailer-cli
docs_url: https://docs.capsailer.dev

# Build settings
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Theme settings
show_downloads: false

# SEO settings
twitter:
  username: capsailer
  card: summary

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/
  - .github/
  - .gitignore
  - README.md
  - LICENSE
 